"""Hyperplane (oblique-split) Decision Tree.

Trains an LMDT on lifted features X' = X @ A where A is a transformation
matrix containing identity rows (axis-aligned splits) plus oblique-
direction rows generated by `hyperplanes.build_transform_matrix`.

The lifted feature space is the substrate for both splits and leaf
linear models, exactly as in upstream.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional, Union

import jax.numpy as jnp
import numpy as np

from jax_ldt._types import Tree
from jax_ldt import tree_core
from jax_ldt._validation import _validate_fit_inputs
from jax_ldt.hyperplanes import build_transform_matrix

ArrayLike = Union[np.ndarray[Any, Any], jnp.ndarray]


@dataclass
class HyperplaneTreeRegressor:
    """Hyperplane Decision Tree (oblique splits).

    Piecewise-linear regression surrogate that lifts inputs into an
    enlarged feature space ``X' = X @ A`` (with ``A`` built by
    :func:`jax_ldt.hyperplanes.build_transform_matrix`) so splits can
    follow oblique directions, not just axis-aligned cuts. The first
    ``n_features_in`` columns of ``A`` are the identity, so axis-aligned
    splits remain candidates. Pure-JAX port of LLNL's
    ``HyperplaneTreeRegressor`` from ``hyperplanetree``. The right
    default for ≥ 2D problems; use :class:`LinearTreeRegressor` for 1D.

    Parameters
    ----------
    criterion : str, default ``"mae"``
        Split-loss criterion. One of ``"mae"``, ``"rmse"``, ``"msle"``,
        ``"max_abs"``.
    max_depth : int, default ``32``
        Maximum tree depth (root is depth 0). Practical sweet spot is
        5-8; deeper trees overfit before they help.
    min_samples_split : int or float, default ``6``
        Minimum samples in a node required to attempt a split. Floats
        in ``(0, 1)`` are fractions of the training-set size.
    min_samples_leaf : int or float, default ``0.01``
        Minimum samples per child leaf. Floats in ``(0, 1)`` are
        fractions of the training-set size; a hard floor of 3 is
        applied to keep the leaf ridge fit well-posed.
    max_bins : int, default ``10``
        Quantile bins per split feature. Lower than the LMDT default
        because the lifted feature space is larger.
    min_impurity_decrease : float, default ``0.0``
        Minimum loss reduction required to accept a split.
    categorical_features : tuple of int, optional
        Column indices treated as categorical (excluded from splitting
        and the linear leaf model).
    linear_features : tuple of int, optional
        Indices in the **transformed** feature space included in the
        leaf linear model. Defaults to every non-categorical lifted
        column. Note: indexing is over ``X'``, not ``X``.
    split_features : tuple of int, optional
        Indices in the **transformed** feature space eligible for
        splitting. Defaults to every non-categorical lifted column.
    ridge : float, default ``1e-5``
        Ridge regularisation added to ``XᵀWX`` before each leaf solve.
    depth_first : bool, default ``True``
        Depth-first grow order if ``True``; breadth-first otherwise.
    num_terms : int, default ``2``
        Features combined per oblique direction. Keep at ``2`` for 6+
        feature problems; higher values explode lifted-feature count
        combinatorially.
    max_weight : int, default ``1``
        Integer-weight cap in the Miller-index hyperplane enumeration.
        Practical range is ``{1, 2}``.
    do_symmetrize : bool, default ``True``
        Apply ±-parity and column permutations, then dedup, when
        building the transform.
    do_scaling : bool, default ``True``
        Rescale each oblique row by training feature ranges so oblique
        angles aren't dominated by feature units.
    tol_decimals : int, default ``4``
        Rounding precision used to dedup near-identical hyperplane rows.
    hyperplane_weights : jnp.ndarray, optional
        Pre-built weight rows (shape ``(n_LCs, num_terms)``) overriding
        the Miller enumeration.

    Attributes
    ----------
    tree_ : Tree
        Fitted tree pytree. ``None`` until :meth:`fit` is called.
    n_features_in_ : int
        Number of input features observed at fit time.
    n_targets_ : int
        Number of regression targets.
    """

    criterion: str = "mae"
    max_depth: int = 32
    min_samples_split: Union[int, float] = 6
    min_samples_leaf: Union[int, float] = 0.01
    max_bins: int = 10
    min_impurity_decrease: float = 0.0
    categorical_features: Optional[tuple[int, ...]] = None
    linear_features: Optional[tuple[int, ...]] = None
    split_features: Optional[tuple[int, ...]] = None
    ridge: float = 1e-5
    depth_first: bool = True

    # Hyperplane-specific knobs
    num_terms: int = 2
    max_weight: int = 1
    do_symmetrize: bool = True
    do_scaling: bool = True
    tol_decimals: int = 4
    hyperplane_weights: Optional[jnp.ndarray] = None

    # populated after fit
    tree_: Optional[Tree] = field(default=None, init=False, repr=False)
    n_features_in_: Optional[int] = field(default=None, init=False, repr=False)
    n_targets_: Optional[int] = field(default=None, init=False, repr=False)

    def fit(self, X: ArrayLike, y: ArrayLike) -> "HyperplaneTreeRegressor":
        # Materialise as JAX arrays first (preserving dtype) so the
        # validator can warn on non-float64 inputs, then upcast.
        X = jnp.asarray(X)
        y = jnp.asarray(y)
        _validate_fit_inputs(X, y)
        X = X.astype(jnp.float64)
        y = y.astype(jnp.float64)
        self.n_features_in_ = int(X.shape[1])
        self.n_targets_ = 1 if y.ndim == 1 else int(y.shape[1])

        A = build_transform_matrix(
            X,
            num_terms=self.num_terms,
            max_weight=self.max_weight,
            LCs=self.hyperplane_weights,
            do_symmetrize=self.do_symmetrize,
            do_scaling=self.do_scaling,
            tol_decimals=self.tol_decimals,
            categorical_features=self.categorical_features,
        )

        self.tree_ = tree_core.grow_tree(
            X,
            y,
            transform_matrix=A,
            linear_features=self.linear_features,
            split_features=self.split_features,
            categorical_features=self.categorical_features,
            criterion=self.criterion,
            max_depth=self.max_depth,
            max_bins=self.max_bins,
            min_samples_split=self.min_samples_split,
            min_samples_leaf=self.min_samples_leaf,
            min_impurity_decrease=self.min_impurity_decrease,
            ridge=self.ridge,
            depth_first=self.depth_first,
        )
        return self

    def predict(self, X: ArrayLike) -> jnp.ndarray:
        if self.tree_ is None:
            raise RuntimeError("Call fit() before predict().")
        X = jnp.asarray(X, dtype=jnp.float64)
        from jax_ldt._validation import _validate_predict_input
        _validate_predict_input(X, self.n_features_in_)
        return tree_core.predict(self.tree_, X)

    def apply(self, X: ArrayLike) -> jnp.ndarray:
        if self.tree_ is None:
            raise RuntimeError("Call fit() before apply().")
        X = jnp.asarray(X, dtype=jnp.float64)
        from jax_ldt._validation import _validate_predict_input
        _validate_predict_input(X, self.n_features_in_)
        return tree_core.apply_tree(self.tree_, X)

    @property
    def num_leaves(self) -> int:
        if self.tree_ is None:
            raise RuntimeError("Call fit() before querying num_leaves.")
        return self.tree_.n_leaves

    @property
    def n_leaves(self) -> int:
        """Alias for :attr:`num_leaves` (matches ``Tree.n_leaves``)."""
        return self.num_leaves

    @property
    def transform_matrix_(self) -> jnp.ndarray:
        if self.tree_ is None:
            raise RuntimeError("Call fit() before reading transform_matrix_.")
        return self.tree_.transform_matrix
